### ISSUE TITLE
How to get single-cell Hi-C data from Li2019's data on GEO

### ISSUE THREAD

**Issue by lhqxinghun** [sshen82/BandNorm_and_scVI-3D_manuscript#1]
Hello,
Thank you for developing BandNorm and scVI-3D which I think will be a wonderful tool in the domain of single-cell Hi-C.
I noticed that you have used the single-cell Hi-C data from Li2019's data (GSE 119171 on GEO) in your manuscript. I am also interested in this dataset and want to get single-cell Hi-C data of each cell from it. However, I find the GSE119171 on GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE119171) only contains a "GSE119171_JL.merged.sorted.nodup.long.juice.q30.hic" and a "GSE119171_RAW.tar". The former seems to be bulk Hi-C not for single-cell Hi-C of each cell, and the latter only contains methylation data. So I have problems in getting single-cell Hi-C data (Hi-C matrix or its sparsed format) from the GSE119171. Would you please kindly tell me how to get it.
Thank you!

**Comment by sshen82** [comment]
Hi,
Thank you for your question! For this data, it is indeed not on GEO. If you only need 1Mb, you can download it from here https://pages.stat.wisc.edu/~sshen82/bandnorm/Li2019/.

However, for the processed scHi-C data, I asked Guoqiang Li, the first author, directly via email and he gave me a ftp site containing those files. The site is forbidden now, so you need to ask him (or other co-authors in the paper) for raw data.

Yours sincerely,
Siqi Shen

**Comment by lhqxinghun** [comment]
OKay, thank you very much!

**Comment by Dududu233** [comment]
Dr Shen:
I was lucky enough to download the original sequencing file of Li2019 before the link in your bioxiv died. But I only get `*.filter` files while the `*.fastq` is needed for `juicer` tools.  
What preprocessing do I need to do?

**Comment by sshen82** [comment]
Hi,
Juicer is actually ok with those txt-like files (https://github.com/aidenlab/juicer/wiki/Pre). .txt, .filter, .bed are all ok to put in. The .filter files you have have 16 columns, and they correspond to the "long format". Using Pre function, you can change them into .hic file.

Or, alternatively, since those .filter files are already cleaned and each row is a sequencing read, you can directly bin them with any language you like. (scHiCTools https://github.com/liu-bioinfo-lab/scHiCTools is a nice tool to do that if you are still not sure how to deal with the files.)

Yours sincerely,
Siqi Shen

**Comment by Dududu233** [comment]
Dr Shen:
Thank you for your quick and conscientious reply. I still have doubts about the second way. The coordinates of the loci in the file I downloaded (pos1 and pos2 in long format) are very close, even less than 1k. So I'm not sure,  should I do something before bin directly?
![filter files I download before](https://user-images.githubusercontent.com/86656612/199024601-86159b7a-6904-428b-9cd4-2ba2ca1b5cb4.png)

**Comment by sshen82** [comment]
As we talked about in the article, there are a lot more interactions on the diagonal than off-diagonal, so it is expected that those two columns are close. When processing this data, I didn't do any other filtering, directly used Juicer, and the result is quite consistent with the tSNE result in the paper.

**Comment by Dududu233** [comment]
Dr Shen:
Thanks for your kindly reply! It really helps me a lot!
